---
# tasks file for wordpress

      - name: Install supporting applications
        become: yes
        apt: 
          name: "{{ item }}"
          state: present
          update_cache: yes
        loop:
          - apache2
          - mysql-server
          - php7.2-mysql
          - php7.2
          - libapache2-mod-php7.2
          - python-mysqldb
          - php7.2-gd
          - php7.2-ssh2
          - python2.7
          - python-pip
          - python3-pip
          - mysql-client
          
      - name: Start Apache
        service: name=apache2 enabled=yes state=started

      - name: Create MySQL DB
        mysql_db: name="{{ wp_mysql_db }}" state=present
        become: yes
        notify: "start mysql"

  

      - name: Create WordPress mysql user
        mysql_user:
          name: "{{ wp_mysql_user }}"
          password: "{{ wp_mysql_password }}"
          priv: '*.*:ALL'
          login_unix_socket: /var/run/mysqld/mysqld.sock
        become: yes
        notify: "restart mysql"

      - name: Create Wordpress folder
        file:
          path: "/var/www/wordpress"
          state: directory
          owner: "devops"
          group: "root"
          mode: '0755'
        become: yes


      - name: Download and install Wordpress
        become: yes
        unarchive:
          src: https://wordpress.org/latest.tar.gz
          dest: /var/www/
          remote_src: yes

      - name: Update ownership to Apache user
        become: yes
        file:
          path: /var/www/wordpress/
          state: directory
          recurse: yes
          owner: devops

      - name: Set the correct permissions on Wordpress directories
        become: yes
        command: find /var/www/wordpress/ -type d -exec chmod 751 {} \;

      - name: Set the correct permissions for Wordpress files
        become: yes
        command: find /var/www/wordpress/ -type f -exec chmod 641 {} \;
         
      # - name: Update default Apache site
      #   become_user: devops
      #   lineinfile:
      #     path: /etc/apache2/sites-enabled/000-default.conf
      #     state: present
      #     regexp: '(.)+DocumentRoot /var/www/html'
      #     line: 'DocumentRoot /var/www/wordpress'
      #   notify: Restart Apache  

      - name: Copy PHP config file to server
        template:
          src: "wp-config.php.j2"
          dest: "/var/www/wordpress/wp-config.php"
        become: yes

      - name: Set up Apache VirtualHost
        become: yes
        template:
          src: "apache.conf.j2"
          dest: "/etc/apache2/sites-available/wordpress.conf"
        notify: Restart Apache


      # - name: Disable default Apache site
      #   shell: /usr/sbin/a2dissite 000-default.conf
      #   become: yes
      #   notify: Restart Apache


      - name: Enable rewrite module
        become: yes
        shell: /usr/sbin/a2enmod rewrite
        notify: Reload Apache

      - name: Enable new site
        become: yes
        shell: /usr/sbin/a2ensite "wordpress.conf"
        notify: Reload Apache

      # - name: UFW - Allow HTTP on port 8080
      #   ufw:
      #     rule: allow
      #     port: "{{ http_port }}" 
      #     proto: tcp
      #   become: yes
